# Preparing new artifact version
FROM node:18-alpine3.16 as builder

WORKDIR /home/node/artifact
COPY --chown=node:node package*.json ./
RUN npm ci
COPY --chown=node:node . .
CMD [ "npm", "run", "migrations:latest" ]
